import type { Metadata } from 'next';
import '../styles/globals.css';

export const metadata: Metadata = {
  title: "Qwixx",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className="h-svh w-screen min-w-[700px]">
    {children}
    </body>
    </html>
  );
}
